# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy frontend and backend app to Azure

on:
    push:
        branches:
            - release
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and zip apps from /dist
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'

            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build --if-present
                  # npm run test --if-present

            - name: Zip artifacts for deployment
              run: |
                  echo ${GITHUB_WORKSPACE}
                  cd ${GITHUB_WORKSPACE}/dist/apps/concert-api/ && zip ${GITHUB_WORKSPACE}/concert-api-release.zip ./* -r
                  cd ${GITHUB_WORKSPACE}/dist/apps/concert-app/ && zip ${GITHUB_WORKSPACE}/concert-app-release.zip ./* -r

            - name: Upload concert-app artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: concert-app
                  path: concert-app-release.zip

            - name: Upload concert-api artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: concert-api
                  path: concert-api-release.zip

    deploy-concert-app:
        runs-on: ubuntu-latest
        name: Deploy Angular Frontend
        needs: build
        environment:
            name: 'Production'

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: concert-app

            - name: Unzip artifact for deployment
              run: unzip concert-app-release.zip

            - name: Deploy to static azure web app
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
                  # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: 'upload'
                  app_location: '/' # App source code path
                  api_location: '' # Api source code path - optional
                  output_location: 'dist/apps/concert-app' # Built app content directory - optional
                  github_id_token: ${{ steps.idtoken.outputs.result }}

    deploy-concert-api:
        runs-on: ubuntu-latest
        name: Deploy NestJs concert-api backend
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: concert-api

            - name: Unzip artifact for deployment
              run: unzip concert-api-release.zip

            - name: Install dependencies
              run: npm install

            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'ConcertAppApi'
                  slot-name: 'Production'
                  publish-profile: ${{ secrets.NESTJS_PUBLISHPROFILE }}
                  package: .